name: Swift

on:
  push:
    branches: [ async-test ]

jobs:
  test:
    runs-on: macos-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.0.app/Contents/Developer
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      
    steps:
    - uses: actions/checkout@v2    
    - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
    - run: rm ~/.ssh/id_rsa || true
    - run: for ip in $(dig @8.8.8.8 bitbucket.org +short); do ssh-keyscan bitbucket.org,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true 
    - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
    - run: brew update 1> /dev/null 2> /dev/null
    - run: brew install sourcekitten
    - run: brew install coreutils
    - run: echo "ruby-3.0.0" > ~/.ruby-version
    - run: bundle install
    - run: bundle exec rake validate_docs
    - run: bundle exec danger || true
    - run: set -o pipefail
    - run: bundle exec rake build
    - run: bundle exec rake tests
